### ISSUE TITLE
1Blocker Keeps Throwing Error

### ISSUE THREAD

**Issue by philipamour** [yous/YousList#48] opened 2018-04-03 09:45 UTC
Since I've added YousList to 1Blocker, all ads are showing again and I keep getting an error every single time I open 1Blocker:

*The operation couldn't be completed. (WKErrorDomain error 2.)*

**Comment by yous** [comment] 2018-04-04 02:45
Hi, @philipamour! Thanks for the report.

But I can't reproduce that error in 1Blocker, can you please give me more information?

- Did you open [Rules.1blockpkg](https://cdn.rawgit.com/yous/YousList/v20180402/Rules.1blockpkg) tagged with v20180402?
- Currently I enable nothing on 1Blocker but YousList. What do you have filters enabled?

Also try opening the file again after deleting already imported filters.

**Comment by ClementPadovani** [comment] 2018-04-06 19:44
Yeah, I’ve been having the issue for a few months and I stumbled upon an error suggesting that the issue came from the fact I had over 50k rules enabled and that was a no-no.

After disabling a few pre-installed rules (EU and Comments), I managed to get YousList working

**Comment by yous** [comment] 2018-04-07 06:27
Oh yes, I've just noticed that there is a 50,000 filter rules limit.

- https://help.getadblock.com/support/solutions/articles/6000099239-what-is-safari-content-blocking-
- https://www.reddit.com/r/apple/comments/6sr04u/does_ios_11_still_have_a_50k_rule_limit_for/

If that error still occurs when you have enabled less than 50,000 rules, please let me know.

**Comment by SMed79** [comment] 2018-04-07 06:46
https://adblockplus.org/development-builds/experimental-safari-content-blocking-support

> Safari 9 has a limit of 50,000 Content Blocking rules, causing an error to be shown when exceeded: “Extension compilation failed: Too many rules in JSON array.”. If you see this error try disabling some filter list subscriptions. We are working to further compress the Content Blocking rules generated and also hope that Apple will increase this limit in future versions of Safari.

**Comment by ClementPadovani** [comment] 2018-04-28 18:55
Hey,

Following up on the issue. If you upgrade to 1Blocker X, the max rules limit is a thing of the past. 

You can have up to 350k rules. And 50k custom rules

**Comment by yous** [comment] 2018-07-12 04:52
Closing now. If you have a problem again, feel free to open a new issue.

**Closed by yous** 2018-07-12 04:52 UTC
